### ISSUE TITLE
multi head attention

### ISSUE THREAD

**Issue by Young-Sun** [syang1993/gst-tacotron#12]
Hi, again.
The code is set to use mlp_attention, now.
Did the uploaded audio demo samples use mlp_attention?
Have you ever experimented using multi head attention? Do you have any audio samples?

Thanks.

**Comment by syang1993** [comment]
Hi, the `mlp_attention` is part of the multi-head attention. `dot_attention` and `mlp_attention` are two different methods to compute attention weights in multi-head attention. The demo samples are trained using the default settings.

**Comment by Young-Sun** [comment]
Sorry for mis-understand. Yes, both dot_attention and mlp_attenton are in multi-head attention.
I see, the audio samples synthesized using mlp_attention.
Thanks for your fast and kind reply. :-)
