### ISSUE TITLE
core dumped error when preprocessing ljspeech dataset

### ISSUE THREAD

**Issue by wanshun123** [syang1993/gst-tacotron#22]
I have the LJSpeech dataset in /database/LJSpeech-1.0 and am trying to preprocess it as follows:

`sudo python3 preprocess.py --dataset ljspeech
`

This results in the following:

> 2018-11-15 22:40:18.182581: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
> Aborted (core dumped)
> 

Wondering if others have ran into this or it's just an issue with my machine.

**Comment by syang1993** [comment]
Hi, I guess you need to check your environment of your machine to see what happened, especially the tensorflow version.

**Comment by wanshun123** [comment]
Appears to have been an issue with my machine and different versions of tensorflow, CUDA and nvidia drivers - in the end it looks to be running with the following:

CUDA 9.0
tensorflow-gpu 1.5
cuDNN 7.0.4
NVIDIA-SMI 384.81

Using the latest versions of everything failed.
