### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [12,2262,80] vs. [12,2000,80]

### ISSUE THREAD

**Issue by ErnstTmp** [syang1993/gst-tacotron#30]
Hi,
thank you very much for creating Tacotron GST!

I have to run on Titan X, and I had to change the batchsize to 16.

after 32 iteration I get

tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [12,2262,80] vs. [12,2000,80]

Have you seen this before?
I am running Tensorflow 1.12.
Thanks and kind regards
Ernst

**Comment by syang1993** [comment]
@ErnstTmp Hi, it is because your data is too long. `outputs_per_step` * `max_iters` is the maximum number of training data. Your can change the `max_iters` to fit your data or throw these too long data (if there are only a little long sentences).

**Comment by ErnstTmp** [comment]
@syang1993: thanks a lot for the fast answer. I forget to mention I am trying the blizzard2013 dataset. I changed max_iters from 1000 to 600, ut I got the same error.

**Comment by syang1993** [comment]
@ErnstTmp It's the maximum number of your data, you should increase the `max_iters`.  Or you can decrease the `_max_out_length` to make it less than 2000 in blizzard2013.py.

**Comment by ErnstTmp** [comment]
Great, that works - thanks!!!
