### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by Young-Sun** [syang1993/gst-tacotron#8]
@syang1993 It's nice work! :-) The latest demo samples are impressing. How long does it take to GST-Tacotron model using segmented Blizzard2013 datasets? And would you let me know GPU specification?

**Comment by syang1993** [comment]
@Young-Sun Thanks. I trained this model with my friend's Tesla P40 GPU. It takes about 4 days to get this model using bc2013 data.

**Comment by butterl** [comment]
@syang1993  Is it normal to run  model training with 3.8s/step ? the hparam is same ,using THCH30 dataset and 16K with max frame limit set to 1500

**Comment by Young-Sun** [comment]
@syang1993 Thanks for your reply. It would be great help to estimate training time :-)

**Comment by fazlekarim** [comment]
@Young-Sun I took me about 2 seconds per step. So if you want 200k steps, it'll take around 400k seconds.
